"""Import staging: batches and candidates. Phase 6.

Hand-written rather than autogenerated. Autogenerate cannot see the raw-SQL
CHECK constraints and triggers the earlier migrations installed, so it proposes
dropping them every time -- see docs/HANDOFF.md.

Revision ID: 0005_import_staging
Revises: 289da951142d
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005_import_staging"
down_revision = "289da951142d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "import_batches",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("profile", sa.String(length=60), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("notes", sa.Text(), nullable=False, server_default=""),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
        # M3: the same file cannot be imported twice. A uniqueness constraint
        # rather than an application check, because the whole point is that it
        # holds against a double-submitted upload.
        sa.UniqueConstraint("content_hash", name="uq_import_batch_hash"),
    )

    op.create_table(
        "import_candidates",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("batch_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(), nullable=False),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
        sa.Column("merchant", sa.String(length=160), nullable=True),
        sa.Column("amount", sa.Numeric(19, 4), nullable=False),
        sa.Column("fingerprint", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACCEPTED", "REJECTED", "DUPLICATE",
                name="candidate_status", native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("duplicate_of_transaction_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("duplicate_of_candidate_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("suggested_category_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("transaction_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["import_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["duplicate_of_transaction_id"], ["transactions.id"]),
        sa.ForeignKeyConstraint(["duplicate_of_candidate_id"], ["import_candidates.id"]),
        sa.ForeignKeyConstraint(["suggested_category_id"], ["categories.id"]),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "row_number", name="uq_candidate_row"),
    )
    op.create_index("ix_candidate_status", "import_candidates", ["status"])
    op.create_index("ix_candidate_fingerprint", "import_candidates", ["fingerprint"])

    # M1 at the database level: one candidate produces at most one transaction,
    # and no two candidates claim the same one. Acceptance is idempotent in
    # `importing.accept`, but a partial index makes a second copy impossible
    # rather than merely unlikely under a concurrent double-submit.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_candidate_transaction
        ON import_candidates (transaction_id)
        WHERE transaction_id IS NOT NULL
        """
    )

    # A candidate is accepted if and only if it has a transaction. The two
    # fields encode the same fact and drifting apart is the failure that would
    # silently double-post on the next import.
    op.execute(
        """
        ALTER TABLE import_candidates
        ADD CONSTRAINT ck_candidate_accepted_has_transaction
        CHECK (
            (status = 'ACCEPTED' AND transaction_id IS NOT NULL)
            OR (status <> 'ACCEPTED' AND transaction_id IS NULL)
        )
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE import_candidates "
        "DROP CONSTRAINT IF EXISTS ck_candidate_accepted_has_transaction"
    )
    op.execute("DROP INDEX IF EXISTS uq_candidate_transaction")
    op.drop_index("ix_candidate_fingerprint", table_name="import_candidates")
    op.drop_index("ix_candidate_status", table_name="import_candidates")
    op.drop_table("import_candidates")
    op.drop_table("import_batches")
