"""Debt terms on accounts: APR and minimum payment.

Hand-written. Autogenerate cannot see the raw-SQL CHECKs and constraint triggers
that 0002-0005 installed -- it compares the ORM metadata against the live schema,
finds objects the models do not describe, and proposes dropping every one of
them. Running that autogenerated script would take L1, L3 and G1 out of the
database while adding two columns.

Both columns are nullable and no CHECK is added, which keeps the constraint count
at the six the earlier migrations left. There is no sensible non-null default: a
current account has no APR, and a liability whose terms are not known yet is a
real state rather than a zero-rate loan.

Revision ID: 0007_debt_terms
Revises: 0006_merchant_suggestions
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0007_debt_terms"
down_revision = "0006_merchant_suggestions"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # A fraction, not a percentage: 0.199000 is 19.9%. Rates carry more decimal
    # places than money, so this is not NUMERIC(19,4).
    op.add_column("accounts", sa.Column("apr", sa.Numeric(9, 6), nullable=True))
    op.add_column(
        "accounts", sa.Column("minimum_payment", sa.Numeric(19, 4), nullable=True)
    )


def downgrade() -> None:
    op.drop_column("accounts", "minimum_payment")
    op.drop_column("accounts", "apr")
