"""Add the scenarios table.

Only the table. Autogenerate also proposed dropping the CHECK constraints and
indexes that earlier migrations created through raw SQL -- it cannot see them in
the model metadata, so every autogenerated migration will suggest removing them.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "289da951142d"
down_revision: str | None = '4f0d1885fb48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "scenarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("baseline_date", sa.Date(), nullable=False),
        sa.Column("horizon_months", sa.Integer(), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "ALTER TABLE scenarios ADD CONSTRAINT ck_scenario_horizon "
        "CHECK (horizon_months BETWEEN 1 AND 600)"
    )


def downgrade() -> None:
    op.drop_table("scenarios")
