"""initial ledger and planning schema

Revision ID: 7b910155edf7
Revises: 
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7b910155edf7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('CURRENT', 'CASH', 'SAVINGS', 'INVESTMENT', 'LIABILITY', 'INCOME_SOURCE', 'EXPENSE', name='account_kind', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('nature', sa.Enum('ESSENTIAL', 'DISCRETIONARY', name='category_nature', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'POSTED', 'VOIDED', name='transaction_status', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('reverses_id', sa.UUID(), nullable=True),
    sa.Column('reimburses_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reimburses_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['reverses_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_booking_date'), 'transactions', ['booking_date'], unique=False)
    op.create_index('ix_transactions_status_date', 'transactions', ['status', 'booking_date'], unique=False)
    op.create_table('user_profile',
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('reporting_timezone', sa.String(length=64), nullable=False),
    sa.Column('protected_cash_buffer', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('near_term_fallback_days', sa.Integer(), nullable=False),
    sa.Column('near_term_floor_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'FORTNIGHTLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='budget_period', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('rollover_policy', sa.Enum('NONE', 'POSITIVE_ONLY', 'FULL', name='rollover_policy', native_enum=False), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('hard', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expected_income',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('rrule', sa.Text(), nullable=True),
    sa.Column('next_expected_date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_income_next_expected_date'), 'expected_income', ['next_expected_date'], unique=False)
    op.create_table('future_obligations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('rrule', sa.Text(), nullable=True),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('hard', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postings',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=19, scale=8), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postings_account_id'), 'postings', ['account_id'], unique=False)
    op.create_index(op.f('ix_postings_transaction_id'), 'postings', ['transaction_id'], unique=False)
    op.create_table('savings_goals',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'OPTIONAL', name='goal_priority', native_enum=False), nullable=False),
    sa.Column('protected_override', sa.Boolean(), nullable=True),
    sa.Column('planned_contribution', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_contributions',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_contributions_booking_date'), 'goal_contributions', ['booking_date'], unique=False)
    op.create_index(op.f('ix_goal_contributions_goal_id'), 'goal_contributions', ['goal_id'], unique=False)
    op.create_table('obligation_instances',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('fulfilled_by_transaction_id', sa.UUID(), nullable=True),
    sa.Column('match_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fulfilled_by_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['future_obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obligation_id', 'due_date', name='uq_obligation_due')
    )
    op.create_index(op.f('ix_obligation_instances_due_date'), 'obligation_instances', ['due_date'], unique=False)
    op.create_index(op.f('ix_obligation_instances_obligation_id'), 'obligation_instances', ['obligation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligation_instances_obligation_id'), table_name='obligation_instances')
    op.drop_index(op.f('ix_obligation_instances_due_date'), table_name='obligation_instances')
    op.drop_table('obligation_instances')
    op.drop_index(op.f('ix_goal_contributions_goal_id'), table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_booking_date'), table_name='goal_contributions')
    op.drop_table('goal_contributions')
    op.drop_table('savings_goals')
    op.drop_index(op.f('ix_postings_transaction_id'), table_name='postings')
    op.drop_index(op.f('ix_postings_account_id'), table_name='postings')
    op.drop_table('postings')
    op.drop_table('future_obligations')
    op.drop_index(op.f('ix_expected_income_next_expected_date'), table_name='expected_income')
    op.drop_table('expected_income')
    op.drop_table('budgets')
    op.drop_table('user_profile')
    op.drop_index('ix_transactions_status_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_booking_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('categories')
    op.drop_table('accounts')
    # ### end Alembic commands ###
