"""budget effective dating

Revision ID: b96bcefa10c0
Revises: 0003_single_correction_mechanism
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b96bcefa10c0'
down_revision: str | None = '0003_single_correction_mechanism'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_revisions',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('rollover_policy', sa.Enum('NONE', 'POSITIVE_ONLY', 'FULL', name='rollover_policy', native_enum=False), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('rollover_reset', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'effective_from', name='uq_revision_effective')
    )
    op.create_index(op.f('ix_budget_revisions_budget_id'), 'budget_revisions', ['budget_id'], unique=False)
    op.add_column('budgets', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('budgets', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('budgets', 'active')
    op.drop_column('budgets', 'amount')
    op.drop_column('budgets', 'rollover_policy')
    op.drop_column('budgets', 'hard')
    # ### end Alembic commands ###

    # --- constraints autogenerate cannot express -------------------------------

    # B-CFG3: the anchor is required for fortnightly and forbidden otherwise.
    # An accepted-and-ignored anchor on a monthly budget is the worst outcome:
    # the budget resets on the 1st while the user believes it resets on the 25th.
    # (Enum columns are native_enum=False, so they hold the member NAME.)
    op.execute(
        "ALTER TABLE budgets ADD CONSTRAINT ck_budget_anchor_iff_fortnightly "
        "CHECK ((period = 'FORTNIGHTLY') = (anchor_date IS NOT NULL))"
    )
    op.execute(
        "ALTER TABLE budgets ADD CONSTRAINT ck_budget_end_after_start "
        "CHECK (end_date IS NULL OR end_date >= start_date)"
    )
    # A category that is its own parent makes the subtree descent non-terminating.
    op.execute(
        "ALTER TABLE categories ADD CONSTRAINT ck_category_not_self_parent "
        "CHECK (parent_id <> id)"
    )
    # v1 is GBP-only (DECISIONS Q2). The columns for multi-currency exist, but
    # until conversion is implemented a non-GBP posting would silently be summed
    # as though it were sterling.
    op.execute(
        "ALTER TABLE postings ADD CONSTRAINT ck_posting_currency_gbp "
        "CHECK (currency = 'GBP')"
    )
    op.create_index("ix_postings_category_id", "postings", ["category_id"])

    # Cross-table rules a CHECK cannot reach.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION assert_budget_revision_valid() RETURNS trigger AS $$
        DECLARE
            budget_period     varchar;
            budget_start      date;
        BEGIN
            SELECT period, start_date INTO budget_period, budget_start
              FROM budgets WHERE id = NEW.budget_id;

            -- B-CFG1: a daily period is its own rollover window; carrying a day
            -- forward into the next day is just a weekly budget with extra steps,
            -- and it makes DaysRemaining=1 arithmetic meaningless.
            IF budget_period = 'DAILY' AND NEW.rollover_policy <> 'NONE' THEN
                RAISE EXCEPTION
                  'Invariant B-CFG1: daily budget % may not use rollover_policy %',
                  NEW.budget_id, NEW.rollover_policy;
            END IF;

            -- B-CFG2: a revision before the budget exists would apply to periods
            -- outside the chain, which have no defined Remaining.
            IF NEW.effective_from < budget_start THEN
                RAISE EXCEPTION
                  'Invariant B-CFG2: revision effective_from % predates budget start_date %',
                  NEW.effective_from, budget_start;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER budget_revision_check
            BEFORE INSERT OR UPDATE ON budget_revisions
            FOR EACH ROW EXECUTE FUNCTION assert_budget_revision_valid();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS budget_revision_check ON budget_revisions")
    op.execute("DROP FUNCTION IF EXISTS assert_budget_revision_valid()")
    op.drop_index("ix_postings_category_id", table_name="postings")
    op.execute("ALTER TABLE postings DROP CONSTRAINT IF EXISTS ck_posting_currency_gbp")
    op.execute(
        "ALTER TABLE categories DROP CONSTRAINT IF EXISTS ck_category_not_self_parent"
    )
    op.execute("ALTER TABLE budgets DROP CONSTRAINT IF EXISTS ck_budget_end_after_start")
    op.execute(
        "ALTER TABLE budgets DROP CONSTRAINT IF EXISTS ck_budget_anchor_iff_fortnightly"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('hard', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('rollover_policy', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('amount', sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('budgets', 'end_date')
    op.drop_column('budgets', 'start_date')
    op.drop_index(op.f('ix_budget_revisions_budget_id'), table_name='budget_revisions')
    op.drop_table('budget_revisions')
    # ### end Alembic commands ###
