"""Single-user access control. Plan section 14.

The plan is explicit about scope: no enterprise roles, no permissions model, no
bank credentials — but enough that an accidental public deployment does not hand
someone your statements and balances.

So: one password, one session cookie, everything behind it.

The password is never stored. Only a PBKDF2-SHA256 hash lives in configuration,
generated by ``scripts/set_password.py``, which the user runs themselves. The
verification is constant-time, so a wrong password takes the same time to reject
whatever it is.

Sessions are signed with a **separate** ``SESSION_SECRET``, not with the password
hash. An earlier version derived the signing key from the hash, which bought
password-change-revokes-sessions for free but gave the hash a second job: anyone
holding it could mint a valid session rather than merely verify a password. A
password hash should only ever be a verifier.

Revocation is preserved without that coupling by stamping each token with a
short fingerprint of the current hash. Change the password and every existing
token stops matching, while the signing key stays independent of it.

Auth is **off by default**, because the app is local-first and forcing a login on
`localhost` would be friction with no threat model behind it. Setting
``AUTH_PASSWORD_HASH`` turns it on. That default is the risky direction, so the
app says so loudly at startup rather than leaving it implied.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import secrets
import time

from fastapi import Cookie, Depends, HTTPException, Response

from app.config import settings

SESSION_COOKIE = "pfos_session"
#: Long enough not to be a nuisance on a personal device, short enough to matter.
SESSION_MAX_AGE = 60 * 60 * 24 * 14
PBKDF2_ROUNDS = 600_000


def hash_password(password: str, salt: bytes | None = None) -> str:
    """``pbkdf2$rounds$salt$digest``, all base64. Never store the password."""
    salt = salt or secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, PBKDF2_ROUNDS)
    return "$".join(
        [
            "pbkdf2",
            str(PBKDF2_ROUNDS),
            base64.b64encode(salt).decode(),
            base64.b64encode(digest).decode(),
        ]
    )


def verify_password(password: str, encoded: str) -> bool:
    """Constant-time comparison, so a near-miss is not measurably closer."""
    try:
        scheme, rounds, salt_b64, digest_b64 = encoded.split("$")
        if scheme != "pbkdf2":
            return False
        candidate = hashlib.pbkdf2_hmac(
            "sha256",
            password.encode(),
            base64.b64decode(salt_b64),
            int(rounds),
        )
        return hmac.compare_digest(candidate, base64.b64decode(digest_b64))
    except (ValueError, TypeError):
        return False


def auth_enabled() -> bool:
    return bool(settings.auth_password_hash)


def _signing_key() -> bytes:
    """The key sessions are signed with.

    Prefers a dedicated secret. Falls back to deriving one from the password hash
    only so an existing install keeps working after an upgrade -- that path is
    the weakness this separation exists to remove, and the startup check says so.
    """
    if settings.session_secret:
        return hashlib.sha256(settings.session_secret.encode()).digest()
    return hashlib.sha256(
        (settings.auth_password_hash + "|session").encode()
    ).digest()


def password_fingerprint() -> str:
    """A short, non-reversible stamp of the current password hash.

    Carried in every token so that changing the password invalidates existing
    sessions, without the signing key having to depend on the hash.
    """
    return hashlib.sha256(
        (settings.auth_password_hash + "|pv").encode()
    ).hexdigest()[:16]


def issue_session(response: Response, secure: bool = False) -> str:
    """Set a signed session cookie. The payload carries only an expiry."""
    payload = json.dumps(
        {
            "exp": int(time.time()) + SESSION_MAX_AGE,
            "pv": password_fingerprint(),
        }
    ).encode()
    body = base64.urlsafe_b64encode(payload).decode()
    signature = base64.urlsafe_b64encode(
        hmac.new(_signing_key(), body.encode(), hashlib.sha256).digest()
    ).decode()
    token = f"{body}.{signature}"

    response.set_cookie(
        SESSION_COOKIE,
        token,
        max_age=SESSION_MAX_AGE,
        httponly=True,          # not readable from JavaScript
        samesite="lax",         # survives ordinary navigation, blocks cross-site POST
        secure=secure,          # only over HTTPS once it is not localhost
        path="/",
    )
    return token


def clear_session(response: Response) -> None:
    response.delete_cookie(SESSION_COOKIE, path="/")


def session_is_valid(token: str | None) -> bool:
    if not token or "." not in token:
        return False
    body, _, signature = token.partition(".")
    expected = base64.urlsafe_b64encode(
        hmac.new(_signing_key(), body.encode(), hashlib.sha256).digest()
    ).decode()
    if not hmac.compare_digest(signature, expected):
        return False
    try:
        payload = json.loads(base64.urlsafe_b64decode(body))
    except (ValueError, TypeError):
        return False
    if int(payload.get("exp", 0)) <= time.time():
        return False
    # A token issued under a previous password is no longer valid, even though
    # its signature is still good -- the signing key did not change.
    return hmac.compare_digest(
        str(payload.get("pv", "")), password_fingerprint()
    )


def require_session(
    pfos_session: str | None = Cookie(default=None),
) -> None:
    """FastAPI dependency guarding every route that is not public.

    A no-op when auth is disabled, so local development is unaffected.
    """
    if not auth_enabled():
        return
    if not session_is_valid(pfos_session):
        raise HTTPException(status_code=401, detail="authentication required")


#: Convenience alias for router-level use.
Protected = Depends(require_session)


def startup_warning() -> str | None:
    """What to say at startup when the app is unprotected."""
    if auth_enabled():
        return None
    if os.environ.get("PFOS_ALLOW_INSECURE") == "1":
        return None
    return (
        "AUTH IS DISABLED — every balance and transaction is readable by anyone "
        "who can reach this port. Fine on localhost; set AUTH_PASSWORD_HASH "
        "(see scripts/set_password.py) before exposing it to a network."
    )


def session_secret_warning() -> str | None:
    """Flag the fallback signing key, which makes the password hash mintable."""
    if not auth_enabled() or settings.session_secret:
        return None
    return (
        "SESSION_SECRET is not set, so sessions are signed with a key derived "
        "from AUTH_PASSWORD_HASH. That makes the hash able to mint a session, "
        "not just verify a password. Re-run scripts/set_password.py to generate "
        "one."
    )
